config/routes.rb
Rails.application.routes.draw do
  get 'recipie/name'
  get 'recipie/myform'
  

  get 'greeter/hello' => "greeter#hello"
  get 'greeter/goodbye'
  root 'recipie#myform'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipie.rb
#ENV["FOOD2FORK_KEY"] = '2b950a11fae589acf0e691a067f363d8'

class Recipie #< ActiveRecord::Base
  include HTTParty

  base_uri "http://food2fork.com/api"
  default_params key: "2b950a11fae589acf0e691a067f363d8"
  format :json

  def self.for (keyword)
    get( "/search" , query: {q: keyword})["recipes"]
  end
end

app/models/recipiesearch.rb
class Recipiesearch < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/greeter_controller.rb
class GreeterController < ApplicationController
  def hello
  random_names = ["Alex","John","sebestian","drake"]
  @name =  random_names.sample 
  @time = Time.now
  @times_displayed ||= 0
  @times_displayed  += 1
  end
  def goodbye
  
@time = Time.now
  end
end

app/controllers/recipie_controller.rb
class RecipieController < ApplicationController
   
   def name
     
    @search_term = params[:looking_for] || 'chocolate'
    @recipie = Recipie.for(@search_term)
  end
  def myform

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greeter_helper.rb
module GreeterHelper
	def formatted_time (time)
     time.strftime("%I:%M%p")
	end
end

app/helpers/recipie_helper.rb
module RecipieHelper
end

app/views/greeter/goodbye.html.erb
<h1> hello world</h1>


<p>The time is <%= formatted_time(@time) %> </p>

app/views/greeter/hello.html.erb
<h1>Greetings <%= @name %> </h1>

<p>The time is <%= formatted_time(@time) %> </p>

<p>Times Displayed is (<%= @times_displayed %>) </p>
<p><%= link_to "Google", "http://www.google.com"%></p>
<p><%= link_to "Goodbye", greeter_goodbye_path %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe Finder</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipie/myform.html.erb
<h2>Search for recipe</h2>
<%= form_tag recipie_name_path  , method: "get" do %>
 
<p> Search : <%= text_field_tag :looking_for %> </p>
 <%= submit_tag "Enter" %> 
 <% end %>

app/views/recipie/name.html.erb
<h1>Searching for <%= @search_term %></h1>
<!--<p> <%= @recipie %></p> -->
  

  <table>
 <tr>

     <th>Publisher</th>
     <th>Recipe ID </th> 
    <th>Thumbnail</th>
    <th>Title</th>
    <th>Social rank</th>
    
  </tr>
  <% @recipie.each do |recipe| %>
    <tr class=<%= cycle('even','odd') %>>
      <td><%= recipe["publisher"]%></td>
      <td><%= recipe["recipe_id"] %></td>
      <td><%= link_to image_tag(recipe["image_url"]),
                                 
                                 recipe["source_url"] %></td>
      <td><%= link_to (sanitize recipe["title"]), recipe["source_url"] %></td>
      <td><%= recipe["social_rank"] %></td>
    </tr>
  <% end %>



</table>

app/views/recipie/new.html.erb
<%= form_for @search do |f| %>
<div>
	<%= f.label :search %> <br>
	<%= f.text_field :search%>

</div>
<% end %>

app/views/recipie/search.html.erb
<%= form_tag searches_path do %>
  <label for="lookup">Lookup</label>
  <%= text_field_tag :lookup %>
 <%= submit_tag "Submit" %>
<% end %>